### ISSUE TITLE
kubevuln PVC should not be created if persistence is disabled

### ISSUE THREAD

**Issue by headyj** [kubescape/helm-charts#183]
# Description
the kubevuln PVC should not be created if persistence is disabled. Because in case the storage class is configured with dynamic volume provisionning (https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/) the pvc will be in "pending" status, which breaks ArgoCD sync process

```
{{- if and .Values.kubevuln.enabled .Values.kubescape.submit .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.kubevuln.name }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    app: {{ .Values.kubevuln.name }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size.kubevuln }}
  {{- if ne .Values.persistence.storageClass "-" }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
```

# Environment
Version: v1.26

# Expected behavior
PVC is not created if persistence is disabled, ArgoCD is able to be in sync

# Actual Behavior
PVC is created even if persistence is disabled, breaking ArgoCD sync
