### ISSUE TITLE
Support ability to provide history limit in schedulers 

### ISSUE THREAD

**Issue by phyzical** [kubescape/helm-charts#260]
## Overview
We currently run kubescape on fargate nodes. Due to a quirk surrounding cronjob job cleanups, when a job completes its associated node sticks around. this means that we end up paying for lingering nodes i.e
![image](https://github.com/kubescape/helm-charts/assets/5182053/15b594b8-a2a1-4b6a-ba0b-b9181a8a5ab9)

## Problem
Need to be able to provide 
```
kind: CronJob
spec:
 successfulJobsHistoryLimit: 0
 failedJobsHistoryLimit: 1
```
## Solution
by being able to provide these to the helm chart 
```
kind: CronJob
spec:
 successfulJobsHistoryLimit: {{ .Values.kubevulnScheduler.successfulJobsHistoryLimit }}
 failedJobsHistoryLimit: {{ .Values.kubevulnScheduler.failedJobsHistoryLimit }}
```
and default to 
```
successfulJobsHistoryLimit=3
failedJobsHistoryLimit=1
```
## Alternatives
simply running an edit after install will "patch" the problem 

## Additional context
Happy to submit a pr to have the helm do this just let me know

unless theres another way to work around this
