### ISSUE TITLE
kubescape-operator 1.15.x fails when deployed with ArgoCD

### ISSUE THREAD

**Issue by WiktorS** [kubescape/helm-charts#296]
# Description
kubescape-operator 1.15.x helm chart fail when deployed with ArgoCD.
Argo manages chart resources a bit differently, but in most cases it works as expected (https://argo-cd.readthedocs.io/en/stable/user-guide/helm/).
Since 1.15.x `ks-cloud-config` configmap is dynamically updated and marked as "hook" resource. Most likely that makes ArgoCD think it is not needed after successful installation.

# Environment
OS: `alpine 3.18.3` 
Version: `kubescape-operator 1.15.5` 
 
# Steps To Reproduce
Install kubescape-operator helm chart with ArgoCD

# Expected behavior
kubescape-cloud-operator 1.14.5 has no issues.
The issues can be solved in variety of ways:
- create configmap purely in job and not marking it as part of deployment 
- (probably) adding some annotations to configmap (add option to define annotation in helm chart or hardcoded it, https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/#no-prune-resources )
- other?

# Actual Behavior
ArgoCD application definition for kubescape in my deployment
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubescape
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubescape.github.io/helm-charts/
    targetRevision: 1.15.5
    chart: kubescape-operator
    helm:
      values: |
        clusterName: <cut>
        account: <cut>
        server: api.armosec.io
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kubescape
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
When automated prune is disabled the below can be seen (otherwise configmap is removed)
![image](https://github.com/argoproj/argo-cd/assets/1777102/a34e31e3-4de5-4ca8-8fe9-f6caf88e01d2)
![image](https://github.com/argoproj/argo-cd/assets/1777102/67c7a1d0-e19d-4a93-b075-423f328eeb23)

# Additional context
