### ISSUE TITLE
ServiceMonitor.monitoring.coreos.com "prometheus-exporter" is invalid: spec.endpoints: Required value

### ISSUE THREAD

**Issue by dabo-devconsole** [kubescape/helm-charts#390]
# Description
Helm installation fails to deploy the prometheus-exporter ServiceMonitor.

# Environment
OS: Ubuntu 22.04 LTS 
Version: 3.0.3
 
# Steps To Reproduce
1.  --set "capabilities.prometheusExporter=enable" or set value in values.yaml
2. helm install ...
3. install all, but prometheus-exporter
4. error: Error: INSTALL FAILED: failed to create resource: ServiceMonitor.monitoring.coreos.com "prometheus-exporter" is invalid: spec.endpoints: Required value 

# Expected behavior
ServiceMonitor is created

# Actual Behavior
ServiceMonitor is not created
 

# Additional context
The template is missing the required "endpoints" specification.

**Comment by dwertent** [comment]
Do you have the Prometheus operator running in your cluster?

**Comment by dabo-devconsole** [comment]
Yes, the kube-prometheus-stack-operator is running in version v0.71.2 in the cluster.

**Comment by dwertent** [comment]
This is unusual, I'm unable to reproduce the problem. It seems to be working fine without any issues. 
Perhaps we should consider adding the endpoint [here](https://github.com/kubescape/helm-charts/blob/main/charts/kubescape-operator/templates/prometheus-exporter/servicemonitor.yaml#L10) just to be cautious.

**Comment by aminrj** [comment]
Hi,
I am experiencing the same issue but while using Prometheus community Helm chart:
`│ Error: failed to create resource: ServiceMonitor.monitoring.coreos.com "prometheus-exporter" is invalid: spec.endpoints: Required value`

The result is that the pod is in a CrashLoopBackOff:
`prometheus-exporter-f4dc7988f-dmf2d   0/1     CrashLoopBackOff   4 (25s ago)   117s`

**Comment by dabo-devconsole** [comment]
Yes it pretty much looks the same. I'm also using the Prometheus community helm chart, especially the prometheus-community/kube-prometheus-stack.

**Comment by hyo-shin** [comment]
I have also encountered this issue:

Error: failed to create resource: ServiceMonitor.monitoring.coreos.com "prometheus-exporter" is invalid: spec.endpoints: Required value

I agree with @dwertent suggestion that the spec.endpoints might need to be added [here](https://github.com/kubescape/helm-charts/blob/main/charts/kubescape-operator/templates/prometheus-exporter/servicemonitor.yaml#L10).

**Comment by lubgi** [comment]
What's the workaround?

**Comment by dwertent** [comment]
I will look into this today :)

**Comment by l-spork-cc** [comment]
We are experiencing the same problem, we deployed a separate servicemonitor outside of the helm deploymeent as a workaround. The following ressource definition works for us, depending on how the prometheus instance is configured one might also need to add a label for the prometheus selector ( we disabled it completely).

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-exporter
  name: kubescape
  namespace: kubescape
spec:
  endpoints:
    - interval: 30s
      targetPort: 8080
      path: /metrics
  namespaceSelector:
    matchNames:
      - kubescape
  selector:
    matchLabels:
      app: prometheus-exporter
```
