### ISSUE TITLE
Add managing ServiceMonitor parameters to kubescape-prometheus-integrator

### ISSUE THREAD

**Issue by akiryushin** [kubescape/helm-charts#46]
**Manage ServiceMonitor parameter**
We have large kubernetes cluster more than 5000 resources. Current parameters of ServiceMonitor don't suit our infrastructure.

**Implement managing parameters of ServiceMonitor in values**
Like that
```
serviceMonitor:
    enabled: true
    interval: 20m
    scrapeTimeout: 100s
```
