### ISSUE TITLE
Kubescape in ArgoCD always get out of sync (`divisor: '0'`)

### ISSUE THREAD

**Issue by mogaal** [kubescape/helm-charts#531]
# Description

When running kubescape helm chart in ArgoCD 
# Environment

OS: K8S (EKS)
Version: Helm Chart 1.22.0
 
# Steps To Reproduce

Install using ArgoCD as below:

```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubescape
  namespace: argocd
spec:
  project: base-infra
  destination:
    namespace: kubescape
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://kubescape.github.io/helm-charts/
      chart: "kubescape-operator"
      targetRevision: 1.22.0
      helm:
        releaseName: kubescape
  syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
```

# Expected behavior

All resources should keep the sync 

# Actual Behavior

It gets out of sync constantly, as you can see in the image below:

<img width="1676" alt="Screenshot 2024-11-03 at 17 09 30" src="https://github.com/user-attachments/assets/b304d9d4-2d7d-459c-b530-0afcb0f59e68">

The way how I "fixed" it is by telling ArgoCD to ignore those fields:

```
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jqPathExpressions:
      - .spec.template.spec.containers[].env[].valueFrom.resourceFieldRef.divisor
  - group: apps
    kind: DaemonSet
    jqPathExpressions:
      - .spec.template.spec.containers[].env[].valueFrom.resourceFieldRef.divisor
```
 
# Additional context

N/A
